---
title: "usoc_graphsR"
author: "Jen Dykxhoorn"
date: "2022-07-29"
updated: "Mar 2025"
output: word_document
---

```{r install packages, include=FALSE}
install.packages("ggrepel", lib="D:/Rpackages")
install.packages("viridis", lib="D:/Rpackages")
install.packages("tidyverse", lib="D:/Rpackages")
install.packages("ggplot2", lib="D:/Rpackages")
install.packages("ggthemes", lib="D:/Rpackages")
install.packages("tidyverse", lib="D:/Rpackages")
install.packages("RColorBrewer", lib="D:/Rpackages")
install.packages("extrafont", lib="D:/Rpackages")
install.packages("gcookbook", lib="D:/Rpackages")
install.packages("readxl", lib="D:/Rpackages")
install.packages("scales", lib="D:/Rpackages")
#install.packages("patchwork", lib="D:/Rpackages")

# install from GitHub since not on CRAN
install.packages(devtools)
devtools::install_github("JohnCoene/charter")

library("ggthemes")
library("viridis")
library("tidyverse")
library("ggplot2")
library("tidyverse")
library("RColorBrewer")
library("extrafont")
library("gcookbook")
library("readxl")
library("scales")
library("patchwork")
library("formatR")


```

```{r formatting}
windowsFonts("Times" = windowsFont("Times"))

#Need to change the number of decimal places for all following plots
scaleTWO <- function(x) sprintf("%.2f", x)
scaleONE <- function(x) sprintf("%.1f", x)
scaleNO <- function(x) sprintf("%.0f",x) ##THIS IS WHAT I NEED FOR WHOLE NUMBERS! 

```

```{r}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)

```




## CMD mean score 
##Overall

```{r overall_mean bring in data, include=FALSE}

overall_mean <- read.csv(file=".../overall_mean.csv", 
                na.strings = c("NA", " ", "-999"))

overall_mean$Overall <- as.factor(overall_mean$Overall)

```

```{r overall_mean}
ggplot(data = overall_mean, mapping = aes(x = Year, y = Mean, group = Overall)) + 
  labs(x = "Year", y = "Mean CMD score",
       title = "") +
  geom_line(aes(color = Overall, group = Overall), linewidth=1) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Overall, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(4,16) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))   +
  theme(legend.position="bottom") + 
  theme(legend.title = element_blank())+
  theme(legend.background = element_rect(linetype="solid"))+
  theme(axis.text = element_text(size = 14), axis.title=element_text(size = 16), legend.text = element_text(size = 14))


ggsave(".../overall_mean.png", dpi=1200)



```


#Sex

```{r sex_mean bring in data, include=FALSE}

sex_mean <- read.csv(file=".../04_results/sex_mean.csv", 
                na.strings = c("NA", " ", "-999"))

sex_mean$Sex <- as.factor(sex_mean$Sex)



```

```{r sex_mean}
ggplot(data = sex_mean, mapping = aes(x = Year, y = Mean, group = Sex)) + 
  labs(x = "Year", y = "Mean CMD score",
       title = "") +
  geom_line(aes(color = Sex, group = Sex), linewidth=1) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Sex, alpha=0.05)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
    theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(4,16) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))   +
  theme(legend.position="bottom") + 
  theme(legend.title = element_blank())+
  theme(legend.background = element_rect(linetype="solid"))+
  theme(axis.text = element_text(size = 14), axis.title=element_text(size = 16), legend.text = element_text(size = 14))


ggsave(".../sex_mean.png", dpi=1200)


```




############################################### 

## NOW Odds Ratios

## Sex

```{r irr/sex bring in data, include=FALSE}

sex_or <- read.csv(file="C:/Users/uctvjld/OneDrive - University College London/02 UK data/CPRD/01 CMD young people/04_results/sex_or.csv", 
                na.strings = c("NA", " ", "-999"))

sex_or$Sex <- as.factor(sex_or$Sex)

```

```{r sex_or}
ggplot(data = sex_or, mapping = aes(x = Year, y = CMD, group = Sex)) +
  labs(x = "Year", y = "Odds ratio",
       title = "Odds of CMD by sex") +
  geom_line(aes(color = Sex, group = Sex)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Sex, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.5,1.0, 1.5, 2.0), linetype="dotted", color="grey") + 
  ylim(0.5,2.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))

ggsave("...06_figures/sex_or.png")

```

##Age group

```{r age group bring in data, include=FALSE}

agegroup_or <- read.csv(file=".../agegroup_or.csv", 
                na.strings = c("NA", " ", "-999"))

agegroup_or$Age <- as.factor(agegroup_or$Age)

##this deletes empty and NA rows
 agegroup_or<- agegroup_or[!apply(is.na(agegroup) | agegroup == "", 1, all),]

```

```{r agegroup_or}
ggplot(data = agegroup_or, mapping = aes(x = year, y = CMD, group = Age)) + 
      labs(x = "Year", y = "Odd ratio",
       title = "Odds of CMD by age group") +
  geom_line(aes(color = Age, group = Age)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Age, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.5,1.0,1.5,2.0), linetype="dotted", color="grey") + 
  ylim(0.5,2.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../age_or.png")                    


```

## Cohort

```{r cohort_or bring in data, include=FALSE}

cohort_or <- read.csv(file=".../cohort_or.csv", 
                na.strings = c("NA", " ", "-999"))

cohort_or$Cohort <- as.factor(cohort_or$Cohort)

#Delete all the extra columns, all starting with X
cohort_or <- cohort_or %>% 
  select(-starts_with("X"))


```

```{r cohort}
ggplot(data = cohort_or, mapping = aes(x = Year, y = CMD, group = Cohort)) +
    labs(x = "Year", y = "Odds ratios",
       title = "Odds of CMD by cohort") +
  geom_line(aes(color = Cohort, group = Cohort)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Cohort, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.5,1.0,1.5,2.0), linetype="dotted", color="grey") + 
  ylim(0.5,2.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))



ggsave(".../cohort_or.png")

```

## Ethnicity

```{r ethnicity_or bring in data, include=FALSE}

ethnicity_or <- read.csv(file="...ethnicity_or.csv", na.strings = c("NA", " ", "-999"))

ethnicity_or$Ethnicity <- as.factor(ethnicity_or$Ethnicity)

##this deletes empty and NA rows
#Delete all the extra columns, all starting with X
ethnicity_or <- ethnicity_or  %>% select(-starts_with("X"))

```

```{r ethnicity_or}
ggplot(data = ethnicity_or, mapping = aes(x = Year, y = CMD, group = Ethnicity)) + 
      labs(x = "Year", y = "Odds ratio",
       title = "Odds of CMD by ethnicity") +
  geom_line(aes(color = Ethnicity, group = Ethnicity)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Ethnicity, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0), linetype="dotted", color="grey") + 
  ylim(0.0,6.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../ethnicity_or.png")

```

## Country

```{r country bring in data, include=FALSE}

country_or <- read.csv(file="C:/Users/uctvjld/OneDrive - University College London/02 UK data/CPRD/01 CMD young people/04_results/country_or.csv", 
                na.strings = c("NA", " ", "-999"))

#Delete all the extra columns, all starting with X
country_or <- country_or  %>% select(-starts_with("X"))

```

```{r country_or}

ggplot(data = country_or, mapping = aes(x = year, y = CMD, group = Country)) + 
      labs(x = "Year", y = "Odds ratio",
       title = "Odds of CMD by country") +
  geom_line(aes(color = Country, group = Country)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Country, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.5,1.0,1.5,2.0), linetype="dotted", color="grey") + 
  ylim(0.5,2.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))

 
ggsave(".../country_or.png")

```

## Region

```{r region_or bring in data, include=FALSE}

region_or <- read.csv(file="C:/Users/uctvjld/OneDrive - University College London/02 UK data/CPRD/01 CMD young people/04_results/region_or.csv", 
                na.strings = c("NA", " ", "-999"))

#Delete all the extra columns, all starting with X
region_or <- region_or  %>% select(-starts_with("X"))

```

```{r region_or}
ggplot(data = region_or, mapping = aes(x = Year, y = CMD, group = Region)) + 
      labs(x = "Year", y = "Odds ratio",
       title = "Odds of CMD by region") +
  geom_line(aes(color = Region, group = Region)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Region, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 9), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(0.5,1.0,1.5,2.0), linetype="dotted", color="grey") + 
  ylim(0.5,2.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))

ggsave(".../region_prev.png")

```



## CMD mean score 
##Overall

```{r overall_mean bring in data, include=FALSE}

overall_mean <- read.csv(file=".../overall_mean.csv", 
                na.strings = c("NA", " ", "-999"))

overall_mean$Overall <- as.factor(overall_mean$Overall)


```

```{r overall_mean}
ggplot(data = overall_mean, mapping = aes(x = Year, y = Mean, group = Overall)) + 
  labs(x = "Year", y = "Mean CMD score",
       title = "") +
  geom_line(aes(color = Overall, group = Overall), linewidth=1) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Overall, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(4,16) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))   +
  theme(legend.position="bottom") + 
  theme(legend.title = element_blank())+
  theme(legend.background = element_rect(linetype="solid"))+
  theme(axis.text = element_text(size = 14), axis.title=element_text(size = 16), legend.text = element_text(size = 14))


ggsave(".../overall_mean.png", dpi=1200)


```

##Sex

```{r sex_mean bring in data, include=FALSE}

sex_mean <- read.csv(file=".../sex_mean.csv", 
                na.strings = c("NA", " ", "-999"))

sex_mean$Sex <- as.factor(sex_mean$Sex)

##this deletes empty and NA rows
 sex_mean<- sex_mean[!apply(is.na(sex) | sex == "", 1, all),]

```

```{r overall_mean}
ggplot(data = overall_mean, mapping = aes(x = Year, y = Mean, group = Overall)) + 
  labs(x = "Year", y = "Mean CMD score",
       title = "") +
  geom_line(aes(color = Overall, group = Overall), linewidth=1) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Overall, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(4,16) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))   +
  theme(legend.position="bottom") + 
  theme(legend.title = element_blank())+
  theme(legend.background = element_rect(linetype="solid"))+
  theme(axis.text = element_text(size = 14), axis.title=element_text(size = 16), legend.text = element_text(size = 14))


ggsave(".../overall_mean.png", dpi=1200)
```

##Age group

```{r age group bring in data, include=FALSE}

agegroup_mean <- read.csv(file=".../agegroup_mean.csv", 
                na.strings = c("NA", " ", "-999"))

agegroup_mean$Agegroup <- as.factor(agegroup_mean$Agegroup)

##this deletes empty and NA rows
 agegroup_mean<- agegroup_mean[!apply(is.na(Age) | Age == "", 1, all),]


```

```{r cohort_mean}
ggplot(data = agegroup_mean, mapping = aes(x = Year, y = CMD, group = Age)) + 
      labs(x = "Year", y = "Weighted mean",
       title = "Mean CMD score by age group") +
  geom_line(aes(color = Age, group = Age)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Age, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
 geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(0.0,16.0) +  
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../age_mean.png")                    

```


##cohort

```{r cohort_mean bring in data, include=FALSE}

cohort_mean <- read.csv(file="cohort_mean.csv", 
                na.strings = c("NA", " ", "-999"))

cohort_mean$Cohort <- as.factor(cohort_mean$Cohort)

##this deletes empty and NA rows
 cohort_mean<- cohort_mean[!apply(is.na(cohort) | cohort == "", 1, all),]


```

```{r cohort_mean}
ggplot(data = cohort_mean, mapping = aes(x = Year, y = Mean, group = Cohort)) + 
      labs(x = "Year", y = "Mean CMD score (95% CI)",
       title = "") +
  geom_line(aes(color = Cohort, group = Cohort), linewidth=1) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Cohort), alpha=0.15) +
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  ylim(8.8,14.0) +  
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))   +
  theme(legend.position="bottom") + 
  theme(legend.title = element_blank())+
  theme(legend.background = element_rect(linetype="solid"))+
  theme(axis.text = element_text(size = 14), axis.title=element_text(size = 16), legend.text = element_text(size = 14))


ggsave("/cohort_mean.png")                    


```



## Ethnicity

```{r ethnicity_mean bring in data, include=FALSE}

ethnicity_mean <- read.csv(file="...ethnicity_mean.csv", na.strings = c("NA", " ", "-999"))

ethnicity_mean$Ethnicity <- as.factor(ethnicity_mean$Ethnicity)


##this deletes empty and NA rows
#Delete all the extra columns, all starting with X

ethnicity_mean <- ethnicity_mean  %>% select(-starts_with("X"))


```

```{r ethnicity_mean}
ggplot(data = ethnicity_mean, mapping = aes(x = Year, y = CMD, group = Ethnicity)) + 
      labs(x = "Year", y = "Weighted mean",
       title = "Mean CMD score by ethnicity") +
  geom_line(aes(color = Ethnicity, group = Ethnicity)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Ethnicity, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(0.0,16.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../ethnicity_mean.png")

```

## Country

```{r country bring in data, include=FALSE}

country_mean <- read.csv(file=".../country_mean.csv", 
                na.strings = c("NA", " ", "-999"))


country_mean$Country <- as.factor(country_mean$Country)


#Delete all the extra columns, all starting with X
country_mean <- country_mean  %>% select(-starts_with("X"))


```

```{r country_mean}

ggplot(data = country_mean, mapping = aes(x = year, y = CMD, group = Country)) + 
      labs(x = "Year", y = "Weighted mean",
       title = "Mean CMD score by country") +
  geom_line(aes(color = Country, group = Country)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Country, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(0.0,16.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../country_mean.png")

```

## Region

```{r Region bring in data, include=FALSE}

region_mean <- read.csv(file=".../region_mean.csv", 
                na.strings = c("NA", " ", "-999"))


region_mean$Region <- as.factor(region_mean$Region)

#Delete all the extra columns, all starting with X
region_mean <- region_mean  %>% select(-starts_with("X"))

```

```{r region_mean}

ggplot(data = region_mean, mapping = aes(x = year, y = CMD, group = Region)) + 
      labs(x = "Year", y = "Weighted mean",
       title = "Mean CMD score by region") +
  geom_line(aes(color = Region, group = Region)) +
  geom_ribbon(aes(ymin=ci_low, ymax=ci_high, fill = Region, alpha=0.1)) + 
  theme(plot.title = element_text(hjust = 0)) +
  theme_tufte() +
  theme(text=element_text(family="Times", color = "black")) + 
  scale_x_continuous(labels = scaleNO, breaks = c(2009, 2011, 2013, 2015, 2017, 2019)) +
  scale_alpha_continuous(name=NULL, guide = "none") + 
  theme(legend.title = element_blank(), legend.text = element_text(family="Times", size = 10), legend.background = element_blank(), legend.justification = c(1,0), legend.position="bottom") + 
  geom_hline(yintercept=c(5.0,10.0, 15.0), linetype="dotted", color="grey") + 
  ylim(0.0,16.0) + 
  theme(axis.line.x.bottom = element_line(linetype = "solid", color = "black")) + 
  theme(axis.line.y.left = element_line(linetype = "solid", color = "black")) + 
  theme(axis.text = element_text(color = "black"))


ggsave(".../region_mean.png")

```
